fix html for a11y
numerique-gouv/sso-operateur pull request #20
Opened 2023-09-29 14:15 UTC by mjeammet

## 🎯 Objectif

Il y a quelques jours, on a ajouté Sonarqube à notre repo, pour test de l'outil.

Voilà ce que ça donne en première analyse : 
![image](https://github.com/numerique-gouv/sso-operateur/assets/30848497/6a9f749b-0ce9-4fcf-a6b1-b804575c32d9)

Cette PR a pour but de fixer les bugs, qui sont des soucis de HTML qui réduit l'accessibilité du produit. 
et peut-être aussi les codes smells 

## 🔍 Implémentation

- _Une liste des modifications_

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environnement, etc._

## 🏕 Amélioration continue

- _(optionnel) Une liste d'autres modifications pas en lien direct avec la PR_

## 🖼️ Images

_(optionnel) Une ou plusieurs captures d'écran, si pertinent_

2023-10-02 08:18 UTC, tut-tuuut commented on templates/blocks/header.html
> +<ul>
Pas besoin d'ajouter ce `<ul>`, il est déjà dans le template de django-dsfr : 

https://github.com/entrepreneur-interet-general/django-dsfr/blob/main/dsfr/templates/dsfr/header.html#L33

2023-10-02 08:22 UTC, tut-tuuut requested changes
Sonarqube a été un peu vite en besogne :)
J'espère qu'il ne va pas nous embêter à chaque PR à cause de ce `<ul>` inclus dans un template parent… Il n'y a pas de problème dans le HTML généré et servi au client.

2023-10-02 08:25 UTC, mjeammet commented on templates/blocks/header.html
> +<ul>
mais on utilise pas ce header, si ? J'ai l'impression qu'il contient des boutons qui n'existent pas chez nous

2023-10-02 08:27 UTC, mjeammet commented
> Sonarqube a été un peu vite en besogne :) J'espère qu'il ne va pas nous embêter à chaque PR à cause de ce `<ul>` inclus dans un template parent… Il n'y a pas de problème dans le HTML généré et servi au client.

On peut lui dire de lâcher l'affaire avec une erreur en particulier. Mais c'est vrai qu'il est un peu naïf : il pète également les plombs sur nos routes Django qui ne seraient pas sécurisées ... 🤔

2023-10-02 09:13 UTC, tut-tuuut commented on templates/blocks/header.html
> +<ul>
On ne l'utilise pas en tant que tel, mais notre propre template l'`{% extends %}` : si tu regardes dans le HTML généré, il y a bien un `<ul>` autour de nos `<li>`

2023-10-02 15:02 UTC, mjeammet commented on templates/blocks/header.html
> +<ul>
damn

2023-10-02 15:04 UTC, mjeammet commented on templates/blocks/header.html
> +<ul>
effectivement, j'avais pas capté qu'on était dans un block. J'ai supprimé les <ul> en trop !

2023-10-03 08:26 UTC, tut-tuuut approved these changes

2023-10-03 08:26 UTC, merged